/* Ok lets draw the incoming circuit connections graph and see what's up. */

const NAME_MAPPING = {
    'and': "and",
    'Capacitor': "capacitor", 
    'Crossover': "crossover", 
    'Diode': "diode",
    'Junction': "node",
    'NOT': "not",
    'Not': "not",
    'OR': "or",
    'Resistor': "and",
    'Text': "text",
    'Transistor': "transistor",
    'Voltage-AC': "voltage-ac",
    'Voltage-ac': "voltage-ac",
    'Zenor Diode': "diode-zenor",
    'and': "and",
    'antenna': null,
    'capacitor': "capacitor",
    'capacitor-polarized': "capacitor-polarized",
    'capacitor-unpolarized': "capacitor",
    'crossover': "crossover",
    'current': "current_source",
    'diac': "diac",
    'diode': "diode",
    'diode-light_emitting': "diode-light_emitting",
    'fuse': "fuse",
    'gnd': "ground",
    'inductor': "inductor",
    'integrated_circuit': null,
    'integrated_cricuit-ne555': null,
    'junction': "node",
    'junctions': "node",
    'lamp': "null",
    'microphone': "microphone",
    'motor': "motor",
    'nand': "nand",
    'nor': "nor",
    'not': "not",
    'operational_amplifier': "opAmp",
    'optocoupler': null,
    'or': "or",
    'probe-current': null,
    'relay': null,
    'resistor': "resistor",
    'resistor-adjustable': "varistor",
    'resistor-photo': "resistor-photo",
    'schmitt_trigger': null,
    'socket': null, 
    'speaker': "speaker",
    'switch': "switch",
    'terminal': "terminal-pos",
    'text': "text", 
    'thyristor': "thyristor",
    'transformer': "transformer",
    'transistor': 'transistor',
    'transistor-npn': "transistor",
    'transistor-photo': "transistor-photo",
    'triac': "triac",
    'varistor': "varistor", 
    'voltage ac': "voltage-ac", 
    'voltage dc': "voltage-dc", 
    'voltage-ac': "voltage-ac", 
    'voltage-dc': "voltage-dc",
    'voltage-dc_ac': "voltage-ac", 
    'voltage-dc_regulator': "voltage-dc", 
    'voltage_ac': "voltage-ac", 
    'voltage_dc': "voltage-ac", 
    'vss': "terminal-pos", 
    'xor': "xor", 
    'zener': "diode-zenor"
}
